# Generated by Django 4.1.3 on 2022-11-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_tipper_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipper',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
